language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jole1783/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jole1783/docker-react npm run test -- --coverage
